// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TouristСenterLibrary;

namespace TouristСenterLibrary.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("TouristСenterLibrary.Entity.ApplicationType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("ApplicationType");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.CheckpointRoute", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RouteID")
                        .HasColumnType("integer");

                    b.Property<string>("TargetStop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("RouteID");

                    b.ToTable("CheckpointRoute");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClientTelefonNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Middlename")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameOfCompany")
                        .HasColumnType("text");

                    b.Property<int>("PeopleAmount")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.CountableEquipment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("CountableEquipment");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.CountableHikeEquip", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("EquipmentID")
                        .HasColumnType("integer");

                    b.Property<int?>("HikeID")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("HikeID");

                    b.ToTable("CountableHikeEquip");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("EmployeeTelefonNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Middlename")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassportData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RoleID")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("EmployeeTelefonNumber")
                        .IsUnique();

                    b.HasIndex("PassportData")
                        .IsUnique();

                    b.HasIndex("RoleID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.Equipment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.Food", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Food");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.Hike", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("RouteID")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("RouteID");

                    b.ToTable("Hike");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.HikeEquipment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("EquipmentFeatures")
                        .HasColumnType("text");

                    b.Property<int?>("EquipmentID")
                        .HasColumnType("integer");

                    b.Property<int?>("HikeID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("HikeID");

                    b.ToTable("HikeEquipment");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.HikeFood", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("FoodID")
                        .HasColumnType("integer");

                    b.Property<int?>("HikeID")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ShelfLife")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("FoodID");

                    b.HasIndex("HikeID");

                    b.ToTable("HikeFood");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.Instructor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InstructorTelefonNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Middlename")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassportData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("InstructorTelefonNumber")
                        .IsUnique();

                    b.HasIndex("PassportData")
                        .IsUnique();

                    b.ToTable("Instructor");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.InstructorGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("HikeID")
                        .HasColumnType("integer");

                    b.Property<int?>("InstructorID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("HikeID");

                    b.HasIndex("InstructorID");

                    b.ToTable("InstructorGroup");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("ApplicationTypeID")
                        .HasColumnType("integer");

                    b.Property<int?>("ClientID")
                        .HasColumnType("integer");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("integer");

                    b.Property<string>("EquipmentFeatures")
                        .HasColumnType("text");

                    b.Property<DateTime>("FinishTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FoodlFeatures")
                        .HasColumnType("text");

                    b.Property<int?>("HikeID")
                        .HasColumnType("integer");

                    b.Property<int?>("RouteID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WayToTravel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("ApplicationTypeID");

                    b.HasIndex("ClientID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("HikeID");

                    b.HasIndex("RouteID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.Participant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("ClientID")
                        .HasColumnType("integer");

                    b.Property<string>("ClientTelefonNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Middlename")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.ToTable("Participant");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.Route", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberDays")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Route");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.RouteHike", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("FinishBusID")
                        .HasColumnType("integer");

                    b.Property<int?>("FinishID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FinishTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("HaltID")
                        .HasColumnType("integer");

                    b.Property<int?>("RouteID")
                        .HasColumnType("integer");

                    b.Property<int?>("StartBusID")
                        .HasColumnType("integer");

                    b.Property<int?>("StartID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.HasIndex("FinishBusID");

                    b.HasIndex("FinishID");

                    b.HasIndex("HaltID");

                    b.HasIndex("RouteID");

                    b.HasIndex("StartBusID");

                    b.HasIndex("StartID");

                    b.ToTable("RouteHike");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.Transport", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CarNumber")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<int>("SeatCount")
                        .HasColumnType("integer");

                    b.Property<int?>("TransportCompanyID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CarNumber")
                        .IsUnique();

                    b.HasIndex("TransportCompanyID");

                    b.ToTable("Transport");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.TransportCompany", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CompanyTelefonNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("CompanyTelefonNumber")
                        .IsUnique();

                    b.ToTable("TransportCompany");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.CheckpointRoute", b =>
                {
                    b.HasOne("TouristСenterLibrary.Entity.Route", null)
                        .WithMany("Checkpoints")
                        .HasForeignKey("RouteID");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.CountableHikeEquip", b =>
                {
                    b.HasOne("TouristСenterLibrary.Entity.CountableEquipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentID");

                    b.HasOne("TouristСenterLibrary.Entity.Hike", "Hike")
                        .WithMany()
                        .HasForeignKey("HikeID");

                    b.Navigation("Equipment");

                    b.Navigation("Hike");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.Employee", b =>
                {
                    b.HasOne("TouristСenterLibrary.Entity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.Hike", b =>
                {
                    b.HasOne("TouristСenterLibrary.Entity.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteID");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.HikeEquipment", b =>
                {
                    b.HasOne("TouristСenterLibrary.Entity.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentID");

                    b.HasOne("TouristСenterLibrary.Entity.Hike", "Hike")
                        .WithMany()
                        .HasForeignKey("HikeID");

                    b.Navigation("Equipment");

                    b.Navigation("Hike");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.HikeFood", b =>
                {
                    b.HasOne("TouristСenterLibrary.Entity.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodID");

                    b.HasOne("TouristСenterLibrary.Entity.Hike", "Hike")
                        .WithMany()
                        .HasForeignKey("HikeID");

                    b.Navigation("Food");

                    b.Navigation("Hike");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.InstructorGroup", b =>
                {
                    b.HasOne("TouristСenterLibrary.Entity.Hike", "Hike")
                        .WithMany()
                        .HasForeignKey("HikeID");

                    b.HasOne("TouristСenterLibrary.Entity.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorID");

                    b.Navigation("Hike");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.Order", b =>
                {
                    b.HasOne("TouristСenterLibrary.Entity.ApplicationType", "ApplicationType")
                        .WithMany()
                        .HasForeignKey("ApplicationTypeID");

                    b.HasOne("TouristСenterLibrary.Entity.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID");

                    b.HasOne("TouristСenterLibrary.Entity.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID");

                    b.HasOne("TouristСenterLibrary.Entity.Hike", "Hike")
                        .WithMany()
                        .HasForeignKey("HikeID");

                    b.HasOne("TouristСenterLibrary.Entity.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteID");

                    b.Navigation("ApplicationType");

                    b.Navigation("Client");

                    b.Navigation("Employee");

                    b.Navigation("Hike");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.Participant", b =>
                {
                    b.HasOne("TouristСenterLibrary.Entity.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.RouteHike", b =>
                {
                    b.HasOne("TouristСenterLibrary.Entity.Transport", "FinishBus")
                        .WithMany()
                        .HasForeignKey("FinishBusID");

                    b.HasOne("TouristСenterLibrary.Entity.CheckpointRoute", "Finish")
                        .WithMany()
                        .HasForeignKey("FinishID");

                    b.HasOne("TouristСenterLibrary.Entity.CheckpointRoute", "Halt")
                        .WithMany()
                        .HasForeignKey("HaltID");

                    b.HasOne("TouristСenterLibrary.Entity.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteID");

                    b.HasOne("TouristСenterLibrary.Entity.Transport", "StartBus")
                        .WithMany()
                        .HasForeignKey("StartBusID");

                    b.HasOne("TouristСenterLibrary.Entity.CheckpointRoute", "Start")
                        .WithMany()
                        .HasForeignKey("StartID");

                    b.Navigation("Finish");

                    b.Navigation("FinishBus");

                    b.Navigation("Halt");

                    b.Navigation("Route");

                    b.Navigation("Start");

                    b.Navigation("StartBus");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.Transport", b =>
                {
                    b.HasOne("TouristСenterLibrary.Entity.TransportCompany", "TransportCompany")
                        .WithMany()
                        .HasForeignKey("TransportCompanyID");

                    b.Navigation("TransportCompany");
                });

            modelBuilder.Entity("TouristСenterLibrary.Entity.Route", b =>
                {
                    b.Navigation("Checkpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
